//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMing.SettingsExtensions {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMing.SettingsExtensions.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 双击 的本地化字符串。
        /// </summary>
        public static string DoubleClick {
            get {
                return ResourceManager.GetString("DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string Exit_Msg_Button_No {
            get {
                return ResourceManager.GetString("Exit_Msg_Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Exit_Msg_Button_Yes {
            get {
                return ResourceManager.GetString("Exit_Msg_Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定关闭 KanColleViewer？ ( ° △ °|||) 的本地化字符串。
        /// </summary>
        public static string Exit_Msg_Content {
            get {
                return ResourceManager.GetString("Exit_Msg_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KanColleViewer 的本地化字符串。
        /// </summary>
        public static string Exit_Msg_Title {
            get {
                return ResourceManager.GetString("Exit_Msg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经注册过的热键 的本地化字符串。
        /// </summary>
        public static string Hotkey_Is_Already_Registered {
            get {
                return ResourceManager.GetString("Hotkey_Is_Already_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string NotifyIcon_ContextMenu_Exit {
            get {
                return ResourceManager.GetString("NotifyIcon_ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏KanColleViewer 的本地化字符串。
        /// </summary>
        public static string NotifyIcon_ContextMenu_Hide {
            get {
                return ResourceManager.GetString("NotifyIcon_ContextMenu_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示KanColleViewer 的本地化字符串。
        /// </summary>
        public static string NotifyIcon_ContextMenu_Show {
            get {
                return ResourceManager.GetString("NotifyIcon_ContextMenu_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能拓展 的本地化字符串。
        /// </summary>
        public static string Plugin_ToolName {
            get {
                return ResourceManager.GetString("Plugin_ToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册热键失败 的本地化字符串。
        /// </summary>
        public static string Registration_HotKey_Failure {
            get {
                return ResourceManager.GetString("Registration_HotKey_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否在关闭kcv时提示？ 的本地化字符串。
        /// </summary>
        public static string Tool_Enable_ExitTip_CheckBox {
            get {
                return ResourceManager.GetString("Tool_Enable_ExitTip_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出提醒【防手滑 (*゜ロ゜)ノ】 的本地化字符串。
        /// </summary>
        public static string Tool_Enable_ExitTip_Title {
            get {
                return ResourceManager.GetString("Tool_Enable_ExitTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 隐藏/显示 kcv 的热键 的本地化字符串。
        /// </summary>
        public static string Tool_Enable_Hotkey_CheckBox {
            get {
                return ResourceManager.GetString("Tool_Enable_Hotkey_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用热键【老板键 (σﾟ∀ﾟ)σ】 的本地化字符串。
        /// </summary>
        public static string Tool_Enable_Hotkey_Title {
            get {
                return ResourceManager.GetString("Tool_Enable_Hotkey_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否将kcv添加到系统托盘？ 的本地化字符串。
        /// </summary>
        public static string Tool_Enable_NotifyIcon_CheckBox {
            get {
                return ResourceManager.GetString("Tool_Enable_NotifyIcon_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用托盘【不用担心被老板发现任务栏的kcv了 (￣ε(#￣)☆】 的本地化字符串。
        /// </summary>
        public static string Tool_Enable_NotifyIcon_Title {
            get {
                return ResourceManager.GetString("Tool_Enable_NotifyIcon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kcv最小化的时候是否隐藏任务栏上的kcv（需要启用托盘） 的本地化字符串。
        /// </summary>
        public static string Tool_Enable_WindowMiniHideTaskbar_CheckBox {
            get {
                return ResourceManager.GetString("Tool_Enable_WindowMiniHideTaskbar_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化时隐藏任务栏 的本地化字符串。
        /// </summary>
        public static string Tool_Enable_WindowMiniHideTaskbar_Title {
            get {
                return ResourceManager.GetString("Tool_Enable_WindowMiniHideTaskbar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Tool_Hotkey_Set_Confirm {
            get {
                return ResourceManager.GetString("Tool_Hotkey_Set_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Tool_Hotkey_Set_Reset {
            get {
                return ResourceManager.GetString("Tool_Hotkey_Set_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请在下面文本框按下想要设定的热键组合 的本地化字符串。
        /// </summary>
        public static string Tool_Hotkey_Set_Tip {
            get {
                return ResourceManager.GetString("Tool_Hotkey_Set_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前景色 的本地化字符串。
        /// </summary>
        public static string Tool_WindowsTheme_AccentColor {
            get {
                return ResourceManager.GetString("Tool_WindowsTheme_AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景色 的本地化字符串。
        /// </summary>
        public static string Tool_WindowsTheme_ThemeColor {
            get {
                return ResourceManager.GetString("Tool_WindowsTheme_ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置kcv的窗口颜色主题 的本地化字符串。
        /// </summary>
        public static string Tool_WindowsTheme_Title {
            get {
                return ResourceManager.GetString("Tool_WindowsTheme_Title", resourceCulture);
            }
        }
    }
}
