//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMing.SettingsExtensions {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMing.SettingsExtensions.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 全部窗体 的本地化字符串。
        /// </summary>
        public static string AllWindow {
            get {
                return ResourceManager.GetString("AllWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换幽灵模式 的本地化字符串。
        /// </summary>
        public static string ChangeGhostMode {
            get {
                return ResourceManager.GetString("ChangeGhostMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拆分面板Tabs模式下，切换游戏界面和信息栏 的本地化字符串。
        /// </summary>
        public static string ChangeTabs {
            get {
                return ResourceManager.GetString("ChangeTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改变窗体状态 的本地化字符串。
        /// </summary>
        public static string ChangeWindowState {
            get {
                return ResourceManager.GetString("ChangeWindowState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双击 的本地化字符串。
        /// </summary>
        public static string DoubleClick {
            get {
                return ResourceManager.GetString("DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定关闭 KanColleViewer？ ( ° △ °|||) 的本地化字符串。
        /// </summary>
        public static string Exit_Msg_Content {
            get {
                return ResourceManager.GetString("Exit_Msg_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KanColleViewer 的本地化字符串。
        /// </summary>
        public static string Exit_Msg_Title {
            get {
                return ResourceManager.GetString("Exit_Msg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按键功能 的本地化字符串。
        /// </summary>
        public static string FunctionKeys {
            get {
                return ResourceManager.GetString("FunctionKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 的本地化字符串。
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经注册过的热键 的本地化字符串。
        /// </summary>
        public static string Hotkey_Is_Already_Registered {
            get {
                return ResourceManager.GetString("Hotkey_Is_Already_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KanColleViewer 的本地化字符串。
        /// </summary>
        public static string KanColleViewer {
            get {
                return ResourceManager.GetString("KanColleViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置 的本地化字符串。
        /// </summary>
        public static string KeySetting_IsNotSetKey {
            get {
                return ResourceManager.GetString("KeySetting_IsNotSetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按键设置 的本地化字符串。
        /// </summary>
        public static string KeysSetting {
            get {
                return ResourceManager.GetString("KeysSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注：全局热键最好设置多个按键，否则会影响到系统的其他软件正常使用 的本地化字符串。
        /// </summary>
        public static string KeysSettingTip {
            get {
                return ResourceManager.GetString("KeysSettingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按键类型 的本地化字符串。
        /// </summary>
        public static string KeyType {
            get {
                return ResourceManager.GetString("KeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局热键 的本地化字符串。
        /// </summary>
        public static string KeyType_HotKey {
            get {
                return ResourceManager.GetString("KeyType_HotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口快捷键 的本地化字符串。
        /// </summary>
        public static string KeyType_Normal {
            get {
                return ResourceManager.GetString("KeyType_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要打开 的本地化字符串。
        /// </summary>
        public static string NeedToOpen {
            get {
                return ResourceManager.GetString("NeedToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string NotifyIcon_ContextMenu_Exit {
            get {
                return ResourceManager.GetString("NotifyIcon_ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能拓展 的本地化字符串。
        /// </summary>
        public static string Plugin_ToolName {
            get {
                return ResourceManager.GetString("Plugin_ToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按键设置 的本地化字符串。
        /// </summary>
        public static string Plugin_ToolName_keys {
            get {
                return ResourceManager.GetString("Plugin_ToolName_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册热键失败 的本地化字符串。
        /// </summary>
        public static string Registration_HotKey_Failure {
            get {
                return ResourceManager.GetString("Registration_HotKey_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截图 的本地化字符串。
        /// </summary>
        public static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示舰娘一览窗体 的本地化字符串。
        /// </summary>
        public static string ShowShipCatalog {
            get {
                return ResourceManager.GetString("ShowShipCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示装备一览窗体 的本地化字符串。
        /// </summary>
        public static string ShowSlotItemCatalog {
            get {
                return ResourceManager.GetString("ShowSlotItemCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 迷你舰队信息 的本地化字符串。
        /// </summary>
        public static string SimpleFleet {
            get {
                return ResourceManager.GetString("SimpleFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 舰队信息样式 的本地化字符串。
        /// </summary>
        public static string SimpleFleetStyle {
            get {
                return ResourceManager.GetString("SimpleFleetStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 迷你小窗口 的本地化字符串。
        /// </summary>
        public static string SimpleFleetWindow {
            get {
                return ResourceManager.GetString("SimpleFleetWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请在文本框中按下想要设定的按键组合 的本地化字符串。
        /// </summary>
        public static string TextBoxEnterKey {
            get {
                return ResourceManager.GetString("TextBoxEnterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开关游戏声音 的本地化字符串。
        /// </summary>
        public static string ToggleMute {
            get {
                return ResourceManager.GetString("ToggleMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否在关闭kcv时提示？ 的本地化字符串。
        /// </summary>
        public static string Tool_Enable_ExitTip_CheckBox {
            get {
                return ResourceManager.GetString("Tool_Enable_ExitTip_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出提醒【防手滑 (*゜ロ゜)ノ】 的本地化字符串。
        /// </summary>
        public static string Tool_Enable_ExitTip_Title {
            get {
                return ResourceManager.GetString("Tool_Enable_ExitTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否将kcv添加到系统托盘？ 的本地化字符串。
        /// </summary>
        public static string Tool_Enable_NotifyIcon_CheckBox {
            get {
                return ResourceManager.GetString("Tool_Enable_NotifyIcon_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用托盘【不用担心被老板发现任务栏的kcv了 (￣ε(#￣)☆】 的本地化字符串。
        /// </summary>
        public static string Tool_Enable_NotifyIcon_Title {
            get {
                return ResourceManager.GetString("Tool_Enable_NotifyIcon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kcv最小化的时候是否隐藏任务栏上的kcv（需要启用托盘） 的本地化字符串。
        /// </summary>
        public static string Tool_Enable_WindowMiniHideTaskbar_CheckBox {
            get {
                return ResourceManager.GetString("Tool_Enable_WindowMiniHideTaskbar_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化时隐藏任务栏 的本地化字符串。
        /// </summary>
        public static string Tool_Enable_WindowMiniHideTaskbar_Title {
            get {
                return ResourceManager.GetString("Tool_Enable_WindowMiniHideTaskbar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示简化版的一号舰队信息 的本地化字符串。
        /// </summary>
        public static string Tool_EnableSimpleFleet_CheckBox {
            get {
                return ResourceManager.GetString("Tool_EnableSimpleFleet_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示一号舰队信息【肝船用 (σﾟ∀ﾟ)σ】 的本地化字符串。
        /// </summary>
        public static string Tool_EnableSimpleFleet_Title {
            get {
                return ResourceManager.GetString("Tool_EnableSimpleFleet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待舰队信息载入中... 的本地化字符串。
        /// </summary>
        public static string Tool_SimpleFleet_Loading {
            get {
                return ResourceManager.GetString("Tool_SimpleFleet_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前景色 的本地化字符串。
        /// </summary>
        public static string Tool_WindowsTheme_AccentColor {
            get {
                return ResourceManager.GetString("Tool_WindowsTheme_AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景色 的本地化字符串。
        /// </summary>
        public static string Tool_WindowsTheme_ThemeColor {
            get {
                return ResourceManager.GetString("Tool_WindowsTheme_ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置kcv的窗口颜色主题 的本地化字符串。
        /// </summary>
        public static string Tool_WindowsTheme_Title {
            get {
                return ResourceManager.GetString("Tool_WindowsTheme_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置工具栏位置 的本地化字符串。
        /// </summary>
        public static string Tool_WindowViewType_Title {
            get {
                return ResourceManager.GetString("Tool_WindowViewType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
