//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMing.Warning {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMing.Warning.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 需要监听的舰队 的本地化字符串。
        /// </summary>
        public static string EnableFleet_Title {
            get {
                return ResourceManager.GetString("EnableFleet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第一舰队 的本地化字符串。
        /// </summary>
        public static string EnableFleet1_CheckBox {
            get {
                return ResourceManager.GetString("EnableFleet1_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第二舰队 的本地化字符串。
        /// </summary>
        public static string EnableFleet2_CheckBox {
            get {
                return ResourceManager.GetString("EnableFleet2_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第三舰队 的本地化字符串。
        /// </summary>
        public static string EnableFleet3_CheckBox {
            get {
                return ResourceManager.GetString("EnableFleet3_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第四舰队 的本地化字符串。
        /// </summary>
        public static string EnableFleet4_CheckBox {
            get {
                return ResourceManager.GetString("EnableFleet4_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string EnableThemeWarning_CheckBox {
            get {
                return ResourceManager.GetString("EnableThemeWarning_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告主题(Kcv红色主题) 的本地化字符串。
        /// </summary>
        public static string EnableThemeWarning_Title {
            get {
                return ResourceManager.GetString("EnableThemeWarning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用(禁用将关闭插件的所有大破警告) 的本地化字符串。
        /// </summary>
        public static string EnableWarning_CheckBox {
            get {
                return ResourceManager.GetString("EnableWarning_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 舰娘大破警告 的本地化字符串。
        /// </summary>
        public static string EnableWarning_Title {
            get {
                return ResourceManager.GetString("EnableWarning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用其他插件的警告通知 的本地化字符串。
        /// </summary>
        public static string EnableWarningEx_CheckBox {
            get {
                return ResourceManager.GetString("EnableWarningEx_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告通知扩展 的本地化字符串。
        /// </summary>
        public static string EnableWarningEx_Title {
            get {
                return ResourceManager.GetString("EnableWarningEx_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用右下角大破警告窗体 的本地化字符串。
        /// </summary>
        public static string EnableWindows_CheckBox {
            get {
                return ResourceManager.GetString("EnableWindows_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 舰娘大破列表 的本地化字符串。
        /// </summary>
        public static string EnableWindows_Title {
            get {
                return ResourceManager.GetString("EnableWindows_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string FilterInRepairing_CheckBox {
            get {
                return ResourceManager.GetString("FilterInRepairing_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略入渠中的大破舰娘 的本地化字符串。
        /// </summary>
        public static string FilterInRepairing_Title {
            get {
                return ResourceManager.GetString("FilterInRepairing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大破警告 的本地化字符串。
        /// </summary>
        public static string Plugin_ToolName {
            get {
                return ResourceManager.GetString("Plugin_ToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 队伍中有舰娘处于大破危险状态，请勿进击 的本地化字符串。
        /// </summary>
        public static string Warning_Content {
            get {
                return ResourceManager.GetString("Warning_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大破警告 的本地化字符串。
        /// </summary>
        public static string Warning_Title {
            get {
                return ResourceManager.GetString("Warning_Title", resourceCulture);
            }
        }
    }
}
